# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main # every commit will trigger this yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployMkDocs
  jobs:
  - job: deploy_gh_pages
    displayName: Deploy MkDocs gh_pages
    steps:
    - script: echo Deploy MkDocs gh_pages.
    # force mkdocs version 1.1.2
    # reference: https://github.com/mkdocs/mkdocs/issues/2447
    - pwsh: |
        pip install mkdocs==1.1.2
        pip install mkdocs-material
        mkdocs build
        mkdocs gh-deploy
    

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
