# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none # every commit will trigger this yml

pool:
  vmImage: ubuntu-latest


stages:
- stage: DeployMkDocs
  jobs:
  - job: deploy_gh_pages
    displayName: Deploy MkDocs gh_pages

    variables:
      - group: galletaHong_creds

    steps:
    - checkout: self
      lfs: true
    - script: echo Deploy MkDocs gh_pages.
      
    # force mkdocs version 1.1.2
    # reference: https://github.com/mkdocs/mkdocs/issues/2447
    - script: |
        git config --global user.name "$(galletaHong_userName)"
        git config --global user.email "$(galletaHong_email)"

        echo $(galletaHong_userName)
        echo $(galletaHong_email)
        echo "https://${gltHng_USER}:${gltHng_TOKEN}@github.com/${gltHng_USER}/first_pipline_repo.git"
      displayName: "Configure Git user"
      env:
        gltHng_USER: $(galletaHong_userName)
        gltHng_TOKEN: $(repoToken)
        HOME: $(Agent.TempDirectory)
      


        # git config --global --add url."https://github.com/".insteadOf "git@github.com:"
        # git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"    
        # -

    - pwsh: |
        git remote set-url origin https://$($env:gltHng_USER):$($env:gltHng_TOKEN)@github.com/$($env:gltHng_USER)/first_pipline_repo.git
        git fetch origin gh-pages --depth=1
      displayName: "Update git config settings"
      env:
        gltHng_USER: $(galletaHong_userName)
        gltHng_TOKEN: $(repoToken)
        HOME: $(Agent.TempDirectory)

    - pwsh: |
        git config --global url."https://".insteadOf git://
        git config --global credential.helper store
        git config --list
      displayName: "git config"

    - pwsh: |
        pip install -U mkdocs
        pip install mkdocs-material
      displayName: "Install mkDocs"
      
    ########################################
    # - pwsh: |
    #     pip install mike
    #   displayName: "Install mike"

    # - pwsh: |
    #     git fetch origin gh-pages --depth=1
    #   displayName: "fetch origin gh-pages"
    
    # - pwsh: |
    #     mike deploy --push main
    #   displayName: "Deploy via mike"
    ########################################

    - pwsh: |
        mkdocs build
      displayName: mkdocs build
    
    - pwsh: |
        mkdocs gh-deploy
      displayName: mkdocs deploy