# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
#- main # every commit will trigger this yml
  paths: 
    include: 
    - "docs/*"
    - "mkdocs.yml"
pr:
  paths:
    include:
      - "docs/*"
      - "mkdocs.yml"

pool:
  vmImage: windows-latest


stages:
- stage: DeployMkDocs
  jobs:
  - job: deploy_gh_pages
    displayName: Deploy MkDocs gh_pages

    variables:
      - group: galletaHong_creds

    steps:
    - checkout: self
      lfs: true
    - script: echo Deploy MkDocs gh_pages.

    - script: |
        git config --global user.name "$(galletaHong_userName)"
        git config --global user.email "$(galletaHong_email)"
      displayName: "Configure Git user"

        # git config --global --add url."https://github.com/".insteadOf "git@github.com:"
        # git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"    
    - pwsh: |
        git remote set-url origin https://$($env:gltHng_USER):$($env:gltHng_TOKEN)@github.com/$($env:gltHng_USER)/first_pipline_repo.git
        git fetch origin gh-pages --depth=1
      displayName: "Update git config settings"
      env:
        gltHng_USER: $(galletaHong_userName)
        gltHng_TOKEN: $(repoToken)
        HOME: $(Agent.TempDirectory)

    # - pwsh: |
    #     git config --global url."https://".insteadOf git://
    #     git config --global credential.helper store
    #     git config --list
    #   displayName: "git config"

    - pwsh: |
        pip install -U mkdocs
        pip install mkdocs-material
      displayName: "Install mkDocs"

    - pwsh: |
        mkdocs build
      displayName: mkdocs build
    
    - pwsh: |
        mkdocs gh-deploy
      displayName: mkdocs deploy